development: &defaults
  client_id: 44054827399-fgalrsf4iuooofvtqairifbkp862s9ug.apps.googleusercontent.com
  client_secret: q00q8Z0H2_wfSjmt2-CkRmQW
  issuer: https://accounts.google.com
  redirect_uri: http://op.dev/connect/google

test:
  <<: *defaults

production:
  <<: *defaults
  redirect_uri: https://connect-op.herokuapp.com/connect/google