development: &defaults
  client_id: 44054827399-fgalrsf4iuooofvtqairifbkp862s9ug.apps.googleusercontent.com
  client_secret: q00q8Z0H2_wfSjmt2-CkRmQW
  scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  redirect_uri: http://localhost/connect/google
  authorization_endpoint: https://accounts.google.com/o/oauth2/auth
  token_endpoint: https://accounts.google.com/o/oauth2/token
  check_session_endpoint: https://accounts.google.com/o/oauth2/tokeninfo
  user_info_endpoint: https://www.googleapis.com/oauth2/v1/userinfo

test:
  <<: *defaults

production:
  <<: *defaults
  redirect_uri: https://openid-connect.herokuapp.com/connect/google